[project]
name = 'Energy-Grid-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-nft]
path = 'contracts/energy-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-payments]
path = 'contracts/energy-payments.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-tracking]
path = 'contracts/energy-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.iot-integration]
path = 'contracts/iot-integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
